prometheusOperator:
  enabled: true
  createCustomResource: true
  cleanupCustomResource: false

defaultRules:
  create: true

kubelet:
  enabled: true
  serviceMonitor:
    https: true
    metricRelabelings:
      - action: keep
        regex: container_.* # keep container-level metrics
        sourceLabels: [__name__]
  relabelings:
    - action: replace
      sourceLabels: [__meta_kubernetes_node_name]
      targetLabel: node
  cAdvisor:
    enabled: true
    metricRelabelings: []
    relabelings: []
  kubeStateMetrics:
    enabled: true

nodeExporter:
  enabled: true
  args:
    - --web.listen-address=0.0.0.0:9100
  hostNetwork: true
  volumes: []
  volumeMounts: []
  securityContext:
    privileged: true
  tolerations:
    - operator: Exists

prometheus:
  prometheusSpec:
    service:
      ports:
        - name: grpc
          port: 10901
          targetPort: 10901
    scrapeProtocols:
      - PrometheusText0.0.4
    retention: 30m
    disableCompaction: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ['ReadWriteOnce']
          resources:
            requests:
              storage: 10Gi
    thanos:
      blockSize: 30m
      image: quay.io/thanos/thanos:v0.38.0
      logLevel: debug
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore-config
          key: objstore.yml
    thanosService:
      enabled: true
      clusterIP: ''
    thanosServiceMonitor:
      enabled: true
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - kube-system
            - scientific-workflow
    # Carregar PrometheusRules customizadas
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector:
      matchLabels:
        prometheus-rules: "enabled"

    additionalScrapeConfigs:
      - job_name: 'argo-workflow-controller'
        scrape_interval: 10s
        scrape_timeout: 5s
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - scientific-workflow
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: workflow-controller-metrics
grafana:
  enabled: false
